/**
 * 【自動生成ファイル】直接編集しないこと。
 * 生成元: mail/templates/（base*.html / blocks.html / themes.json）
 * 再生成: プロジェクト直下で node mail/build.mjs
 */

/** メール全体の骨格。themes.json の "base" で選ぶ */
const TEMPLATE_BASES = {
  "default": [
    "<!--",
    "  Stellize HTMLメール 共通テンプレート（骨格）",
    "",
    "  サイトの世界観をメールに持ち込むための取り決め。",
    "    ・地は米色 #F0EBE3、本体は白のカード。角丸と淡い影で「便箋」に見せる",
    "    ・見出しは明朝、字間 0.06em。ここがブランドの背骨なので絶対に崩さない",
    "    ・罫はシャンパンゴールド #C0A16B の細線。太くしない",
    "    ・星 ✦ は区切りと飾りにだけ使う。多用すると安っぽくなる",
    "",
    "  メールクライアント対策として守っている制約。",
    "    1. レイアウトは <table> のみ。flex / grid / position は使わない",
    "    2. 色・余白・文字はすべてインラインstyle。<style> はレスポンシブと",
    "       ダークモードの上書きだけ（Gmailアプリの一部は <style> を捨てるため）",
    "    3. Webフォントは読み込まない。Gmailが対応しないので端末のフォントに任せる",
    "    4. 面のグラデーションは bgcolor（単色）を必ず併記する。",
    "       Outlookは background-image を無視するので、単色でも成立する配色にする",
    "    5. 画像は必ず絶対URL。alt を入れ、画像オフでも意味が通る文にする",
    "",
    "  {{...}} は Render.gs / mail/build.mjs が置換する差し込み口。",
    "-->",
    "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">",
    "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ja\">",
    "<head>",
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "<meta name=\"x-apple-disable-message-reformatting\" />",
    "<meta name=\"color-scheme\" content=\"light\" />",
    "<meta name=\"supported-color-schemes\" content=\"light\" />",
    "<title>{{SUBJECT}}</title>",
    "<!--[if mso]>",
    "<xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>",
    "<![endif]-->",
    "<style type=\"text/css\">",
    "  table, td { mso-table-lspace:0pt; mso-table-rspace:0pt; }",
    "  img { -ms-interpolation-mode:bicubic; border:0; outline:none; text-decoration:none; }",
    "  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }",
    "  a[x-apple-data-detectors] { color:inherit !important; text-decoration:none !important; font-size:inherit !important; font-family:inherit !important; font-weight:inherit !important; line-height:inherit !important; }",
    "",
    "  @media only screen and (max-width:620px) {",
    "    .sl-wrap  { width:100% !important; }",
    "    .sl-pad   { padding-left:26px !important; padding-right:26px !important; }",
    "    .sl-pad-l { padding-left:26px !important; padding-right:26px !important; }",
    "    .sl-h1    { font-size:24px !important; line-height:1.62 !important; letter-spacing:.03em !important; }",
    "    .sl-h2    { font-size:19px !important; }",
    "    .sl-state { font-size:19px !important; line-height:1.85 !important; }",
    "    .sl-lead  { font-size:15.5px !important; }",
    "    .sl-num   { font-size:30px !important; }",
    "    .sl-btn a { display:block !important; padding-left:16px !important; padding-right:16px !important; }",
    "    .sl-stack { display:block !important; width:100% !important; max-width:100% !important; }",
    "    .sl-gap   { display:block !important; height:14px !important; line-height:14px !important; }",
    "    .sl-logo img { width:138px !important; height:auto !important; }",
    "    .sl-spec-key { width:82px !important; }",
    "    .sl-voice-img { width:52px !important; }",
    "  }",
    "",
    "  /* Outlook.com / Outlookアプリ のダークモード。地まで反転されるとゴールドの罫が沈むので、",
    "     明るい面と文字色だけ明示的に戻す */",
    "  [data-ogsc] .sl-card  { background:#FFFFFF !important; }",
    "  [data-ogsc] .sl-cream { background:#FAF7F2 !important; }",
    "  [data-ogsc] .sl-text  { color:#3A3A3A !important; }",
    "  [data-ogsc] .sl-title { color:{{ACCENT}} !important; }",
    "  [data-ogsc] .sl-kicker{ color:#9A7F4E !important; }",
    "</style>",
    "</head>",
    "<body style=\"margin:0; padding:0; background-color:#F0EBE3;\">",
    "",
    "<!-- プリヘッダー：受信箱の一覧で件名の隣に出る文。本文には見せない -->",
    "<div style=\"display:none; font-size:1px; color:#F0EBE3; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all;\">{{PREHEADER}}</div>",
    "<div style=\"display:none; font-size:1px; color:#F0EBE3; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all;\">&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;</div>",
    "",
    "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:#F0EBE3;\">",
    "  <tr>",
    "    <td align=\"center\" style=\"padding:26px 12px 44px 12px;\">",
    "",
    "      <!--[if mso]><table role=\"presentation\" width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td><![endif]-->",
    "      <table role=\"presentation\" class=\"sl-wrap\" width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px; max-width:600px; margin:0 auto;\">",
    "",
    "        <tr>",
    "          <td align=\"center\" style=\"padding:0 24px 14px 24px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:11px; line-height:1.6; color:#9A9184;\">",
    "            {{WEBVIEW}}",
    "          </td>",
    "        </tr>",
    "",
    "        <!-- ロゴとタグライン。ここでブランドを名乗る -->",
    "        <tr>",
    "          <td class=\"sl-logo\" align=\"center\" style=\"padding:0 24px 8px 24px;\">",
    "            <a href=\"{{SITE_URL}}\" style=\"text-decoration:none;\"><img src=\"{{LOGO_URL}}\" width=\"158\" height=\"37\" alt=\"Stellize\" style=\"display:block; width:158px; height:auto; border:0; font-family:'Hiragino Mincho ProN','Yu Mincho',serif; font-size:18px; letter-spacing:0.14em; color:#1F2A54; text-decoration:none;\" /></a>",
    "          </td>",
    "        </tr>",
    "        <tr>",
    "          <td align=\"center\" style=\"padding:0 24px 22px 24px; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','MS PMincho',serif; font-size:11px; letter-spacing:0.34em; color:#9A7F4E; text-indent:0.34em;\">",
    "            自分の価値に、気づく。",
    "          </td>",
    "        </tr>",
    "",
    "        <!-- 本体カード -->",
    "        <tr>",
    "          <td class=\"sl-card\" style=\"background-color:#FFFFFF; border-radius:16px; overflow:hidden;\">",
    "            <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-radius:16px; overflow:hidden;\">",
    "",
    "              <!-- カード上端。テーマ色の細い帯 -->",
    "              <tr><td style=\"height:5px; line-height:5px; font-size:0; background-color:{{ACCENT}};\">&nbsp;</td></tr>",
    "",
    "              <!-- 冒頭画像（原稿に !! があれば入る） -->",
    "              {{HERO}}",
    "",
    "              <!-- 見出しまわり。米色から白へ流して、便箋の書き出しに見せる -->",
    "              <tr>",
    "                <td class=\"sl-cream\" bgcolor=\"#FAF7F2\" style=\"background-color:#FAF7F2; background-image:linear-gradient(180deg,#FAF7F2 0%,#FFFFFF 100%);\">",
    "                  <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
    "                    <tr>",
    "                      <td class=\"sl-pad\" style=\"padding:40px 46px 0 46px;\">",
    "                        <p class=\"sl-kicker\" style=\"margin:0 0 14px 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:10px; letter-spacing:0.24em; color:#9A7F4E; text-indent:0.24em;\">{{EYEBROW}}</p>",
    "                        <h1 class=\"sl-h1 sl-title\" style=\"margin:0; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','MS PMincho',serif; font-size:28px; line-height:1.72; font-weight:600; letter-spacing:0.055em; color:{{ACCENT}};\">{{TITLE}}</h1>",
    "                      </td>",
    "                    </tr>",
    "                    <!-- 星の飾り罫。サイトの star-divider と同じ役 -->",
    "                    <tr>",
    "                      <td class=\"sl-pad\" style=\"padding:22px 46px 40px 46px;\">",
    "                        <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
    "                          <tr>",
    "                            <td style=\"width:54px; height:1px; line-height:1px; font-size:0; background-color:#DFCFA8;\">&nbsp;</td>",
    "                            <td style=\"padding:0 10px; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:11px; line-height:1; color:#C0A16B;\">&#10022;</td>",
    "                            <td style=\"width:54px; height:1px; line-height:1px; font-size:0; background-color:#DFCFA8;\">&nbsp;</td>",
    "                          </tr>",
    "                        </table>",
    "                      </td>",
    "                    </tr>",
    "                  </table>",
    "                </td>",
    "              </tr>",
    "",
    "              <!-- 本文 -->",
    "              {{BODY}}",
    "",
    "              <tr><td style=\"height:14px; line-height:14px; font-size:0;\">&nbsp;</td></tr>",
    "",
    "              <!-- カード下端のゴールド罫 -->",
    "              <tr><td style=\"height:3px; line-height:3px; font-size:0; background-color:#C0A16B;\">&nbsp;</td></tr>",
    "            </table>",
    "          </td>",
    "        </tr>",
    "",
    "        <!-- 差出人情報とフッター",
    "             特定電子メール法で表示が必要な項目。消さないこと。",
    "             ・送信者の名称 ・住所 ・問い合わせ受付先 ・受信拒否の通知先 -->",
    "        <tr>",
    "          <td class=\"sl-pad\" style=\"padding:30px 46px 0 46px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:12px; line-height:1.95; color:#82796C;\">",
    "            {{FOOTER_NOTE}}",
    "            <p style=\"margin:0 0 5px 0; font-family:'Hiragino Mincho ProN','Yu Mincho',serif; font-size:14px; letter-spacing:0.04em; color:#3F3A32;\">{{COMPANY}}</p>",
    "            <p style=\"margin:0 0 2px 0;\">{{ADDRESS}}</p>",
    "            <p style=\"margin:0 0 14px 0;\"><a href=\"{{SITE_URL}}\" style=\"color:{{ACCENT_DEEP}}; text-decoration:underline;\">{{SITE_URL_LABEL}}</a>　|　<a href=\"{{CONTACT_URL}}\" style=\"color:{{ACCENT_DEEP}}; text-decoration:underline;\">お問い合わせ</a>　|　<a href=\"{{PRIVACY_URL}}\" style=\"color:{{ACCENT_DEEP}}; text-decoration:underline;\">プライバシーポリシー</a></p>",
    "            <p style=\"margin:0 0 4px 0; font-size:11px; line-height:1.85; color:#9A9184;\">{{PERMISSION_NOTE}}</p>",
    "            <p style=\"margin:0 0 22px 0; font-size:11px;\"><a href=\"{{UNSUB_URL}}\" style=\"color:#9A9184; text-decoration:underline;\">今後このメールを受け取らない（配信停止）</a></p>",
    "            <p style=\"margin:0 0 6px 0; font-size:10px; letter-spacing:0.06em; color:#B0A79A;\">&copy; {{YEAR}} Stellize. All rights reserved.</p>",
    "          </td>",
    "        </tr>",
    "",
    "      </table>",
    "      <!--[if mso]></td></tr></table><![endif]-->",
    "",
    "    </td>",
    "  </tr>",
    "</table>",
    "{{TRACKING}}",
    "</body>",
    "</html>",
    ""
  ].join('\n'),
  "daily": [
    "<!--",
    "  日刊の骨格。",
    "",
    "  営業レター（base.html）とは目的が違うので、骨格から分けている。",
    "    ・毎日届くものなので、飾りは邪魔になる。ロゴは小さく、タグラインは出さない",
    "    ・ヒーロー画像もCTA帯も使わない。売り込みは月1の営業レターに任せる",
    "    ・そのぶん本文の行間を広く取る（1.5行分）。読み物として最後まで読ませるため",
    "    ・号数と日付を上に出す。毎日届くものは「いつのか」が分かることが親切",
    "",
    "  メールクライアント対策は base.html と同じ制約に従う（理由もそちらに書いてある）。",
    "-->",
    "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">",
    "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ja\">",
    "<head>",
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "<meta name=\"x-apple-disable-message-reformatting\" />",
    "<meta name=\"color-scheme\" content=\"light\" />",
    "<meta name=\"supported-color-schemes\" content=\"light\" />",
    "<title>{{SUBJECT}}</title>",
    "<!--[if mso]>",
    "<xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>",
    "<![endif]-->",
    "<style type=\"text/css\">",
    "  table, td { mso-table-lspace:0pt; mso-table-rspace:0pt; }",
    "  img { -ms-interpolation-mode:bicubic; border:0; outline:none; text-decoration:none; }",
    "  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }",
    "  a[x-apple-data-detectors] { color:inherit !important; text-decoration:none !important; font-size:inherit !important; font-family:inherit !important; font-weight:inherit !important; line-height:inherit !important; }",
    "",
    "  @media only screen and (max-width:620px) {",
    "    .sl-wrap  { width:100% !important; }",
    "    .sl-pad   { padding-left:24px !important; padding-right:24px !important; }",
    "    .sl-h1    { font-size:21px !important; line-height:1.7 !important; }",
    "    .sl-h2    { font-size:18px !important; }",
    "    .sl-state { font-size:18px !important; line-height:1.9 !important; }",
    "    .sl-lead  { font-size:15.5px !important; }",
    "    .sl-num   { font-size:28px !important; }",
    "    .sl-btn a { display:block !important; padding-left:16px !important; padding-right:16px !important; }",
    "    .sl-stack { display:block !important; width:100% !important; max-width:100% !important; }",
    "    .sl-logo img { width:104px !important; height:auto !important; }",
    "    .sl-spec-key { width:82px !important; }",
    "    .sl-voice-img { width:52px !important; }",
    "    .sl-dateline { display:block !important; padding-top:6px !important; text-align:left !important; }",
    "  }",
    "",
    "  [data-ogsc] .sl-card  { background:#FFFFFF !important; }",
    "  [data-ogsc] .sl-cream { background:#FAF7F2 !important; }",
    "  [data-ogsc] .sl-text  { color:#3A3A3A !important; }",
    "  [data-ogsc] .sl-title { color:{{ACCENT}} !important; }",
    "</style>",
    "</head>",
    "<body style=\"margin:0; padding:0; background-color:#F2EDE5;\">",
    "",
    "<div style=\"display:none; font-size:1px; color:#F2EDE5; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all;\">{{PREHEADER}}</div>",
    "<div style=\"display:none; font-size:1px; color:#F2EDE5; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all;\">&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;&#8199;&#65279;&#847;</div>",
    "",
    "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:#F2EDE5;\">",
    "  <tr>",
    "    <td align=\"center\" style=\"padding:22px 12px 40px 12px;\">",
    "",
    "      <!--[if mso]><table role=\"presentation\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td><![endif]-->",
    "      <table role=\"presentation\" class=\"sl-wrap\" width=\"580\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:580px; max-width:580px; margin:0 auto;\">",
    "",
    "        <!-- 題字。ロゴを小さく、左に。右に号と日付 -->",
    "        <tr>",
    "          <td style=\"padding:0 4px 14px 4px;\">",
    "            <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
    "              <tr>",
    "                <td class=\"sl-logo\" valign=\"middle\" align=\"left\" style=\"padding:0;\">",
    "                  <a href=\"{{SITE_URL}}\" style=\"text-decoration:none;\"><img src=\"{{LOGO_URL}}\" width=\"118\" height=\"28\" alt=\"Stellize\" style=\"display:block; width:118px; height:auto; border:0; font-family:'Hiragino Mincho ProN','Yu Mincho',serif; font-size:15px; letter-spacing:0.12em; color:#1F2A54; text-decoration:none;\" /></a>",
    "                </td>",
    "                <td class=\"sl-dateline\" valign=\"middle\" align=\"right\" style=\"font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:10.5px; letter-spacing:0.1em; color:#9A9184;\">",
    "                  {{DATELINE}}",
    "                </td>",
    "              </tr>",
    "            </table>",
    "          </td>",
    "        </tr>",
    "",
    "        <!-- 本体 -->",
    "        <tr>",
    "          <td class=\"sl-card\" style=\"background-color:#FFFFFF; border-radius:12px; overflow:hidden;\">",
    "            <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-radius:12px; overflow:hidden;\">",
    "",
    "              <tr><td style=\"height:3px; line-height:3px; font-size:0; background-color:{{ACCENT}};\">&nbsp;</td></tr>",
    "",
    "              <tr>",
    "                <td class=\"sl-pad\" style=\"padding:34px 44px 0 44px;\">",
    "                  <p style=\"margin:0 0 12px 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:10px; letter-spacing:0.22em; color:#9A7F4E; text-indent:0.22em;\">{{EYEBROW}}</p>",
    "                  <h1 class=\"sl-h1 sl-title\" style=\"margin:0; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','MS PMincho',serif; font-size:24px; line-height:1.78; font-weight:600; letter-spacing:0.045em; color:{{ACCENT}};\">{{TITLE}}</h1>",
    "                </td>",
    "              </tr>",
    "              <tr>",
    "                <td class=\"sl-pad\" style=\"padding:20px 44px 6px 44px;\">",
    "                  <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"width:40px; height:2px; line-height:2px; font-size:0; background-color:#C0A16B;\">&nbsp;</td></tr></table>",
    "                </td>",
    "              </tr>",
    "",
    "              {{HERO}}",
    "              {{BODY}}",
    "",
    "              <tr><td style=\"height:16px; line-height:16px; font-size:0;\">&nbsp;</td></tr>",
    "            </table>",
    "          </td>",
    "        </tr>",
    "",
    "        <!-- フッター。毎日届くので短く。ただし法令上必要な項目は落とさない",
    "             ・送信者の名称 ・住所 ・問い合わせ受付先 ・受信拒否の通知先 -->",
    "        <tr>",
    "          <td class=\"sl-pad\" style=\"padding:24px 44px 0 44px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:11.5px; line-height:1.9; color:#8A8072;\">",
    "            {{FOOTER_NOTE}}",
    "            <p style=\"margin:0 0 3px 0;\">{{COMPANY}}　{{ADDRESS}}</p>",
    "            <p style=\"margin:0 0 12px 0;\"><a href=\"{{SITE_URL}}\" style=\"color:{{ACCENT_DEEP}}; text-decoration:underline;\">{{SITE_URL_LABEL}}</a>　|　<a href=\"{{CONTACT_URL}}\" style=\"color:{{ACCENT_DEEP}}; text-decoration:underline;\">お問い合わせ</a>　|　<a href=\"{{PRIVACY_URL}}\" style=\"color:{{ACCENT_DEEP}}; text-decoration:underline;\">プライバシーポリシー</a></p>",
    "            <p style=\"margin:0 0 3px 0; font-size:10.5px; line-height:1.8; color:#A39B8F;\">{{PERMISSION_NOTE}}</p>",
    "            <p style=\"margin:0 0 16px 0; font-size:10.5px;\">{{WEBVIEW}}　<a href=\"{{UNSUB_URL}}\" style=\"color:#A39B8F; text-decoration:underline;\">配信を停止する</a></p>",
    "            <p style=\"margin:0 0 6px 0; font-size:10px; letter-spacing:0.06em; color:#B8B0A3;\">&copy; {{YEAR}} Stellize.</p>",
    "          </td>",
    "        </tr>",
    "",
    "      </table>",
    "      <!--[if mso]></td></tr></table><![endif]-->",
    "",
    "    </td>",
    "  </tr>",
    "</table>",
    "{{TRACKING}}",
    "</body>",
    "</html>",
    ""
  ].join('\n')
};

/** 本文ブロック集（blocks.html） */
const TEMPLATE_BLOCKS = [
  "<!--",
  "  本文ブロック集。base.html の {{BODY}} に、この中の <tr> を並べて入れる。",
  "",
  "  ・「<!-- @block 名前 -->」から次の @block までが1単位",
  "  ・{{...}} は差し込み口。{{ACCENT}} 系はテーマ（配色）から来る",
  "  ・原則すべて <tr> で始まる。base.html 側のテーブルの行として積むため",
  "  ・「全幅」と書いてあるブロックは左右の余白を持たず、カードの端まで色を敷く",
  "",
  "  ブロックを増やすときは、ここに @block を足し、render.js の",
  "  slzParseBody / slzRenderBlocks に対応を書く。",
  "-->",
  "",
  "<!-- @block lead -->",
  "<!-- 書き出しの一段落。ここだけ大きくして、読み始めの負荷を下げる -->",
  "<tr>",
  "  <td class=\"sl-pad sl-text sl-lead\" style=\"padding:2px 46px 0 46px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:16.5px; line-height:2.15; letter-spacing:0.015em; color:#33302B;\">",
  "    {{TEXT}}",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block paragraph -->",
  "<tr>",
  "  <td class=\"sl-pad sl-text\" style=\"padding:20px 46px 0 46px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:15px; line-height:2.05; letter-spacing:0.012em; color:#3A3A3A;\">",
  "    {{TEXT}}",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block heading -->",
  "<!-- 中見出し。明朝＋星＋細い罫。サイトの見出しの作りに合わせている -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:42px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      <tr>",
  "        <td width=\"20\" valign=\"middle\" style=\"width:20px; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:11px; line-height:1; color:#C0A16B;\">&#10022;</td>",
  "        <td class=\"sl-h2\" valign=\"middle\" style=\"font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','MS PMincho',serif; font-size:21px; line-height:1.65; font-weight:600; letter-spacing:0.05em; color:{{ACCENT}};\">{{TEXT}}</td>",
  "      </tr>",
  "    </table>",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"height:1px; line-height:1px; font-size:0; background-color:#EDE7DD; padding-top:0;\">&nbsp;</td></tr></table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block subheading -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:28px 46px 0 46px;\">",
  "    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      <tr>",
  "        <td width=\"3\" style=\"width:3px; background-color:#C0A16B; font-size:0; line-height:0;\">&nbsp;</td>",
  "        <td style=\"padding-left:11px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:14px; font-weight:600; line-height:1.7; letter-spacing:0.05em; color:{{ACCENT_DEEP}};\">{{TEXT}}</td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block list -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:16px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      {{ITEMS}}",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block list-item -->",
  "<tr>",
  "  <td width=\"20\" valign=\"top\" style=\"width:20px; padding:5px 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:11px; line-height:2.5; color:#C0A16B;\">&#9670;</td>",
  "  <td valign=\"top\" class=\"sl-text\" style=\"padding:5px 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:15px; line-height:1.95; color:#3A3A3A;\">{{TEXT}}</td>",
  "</tr>",
  "",
  "<!-- @block check-item -->",
  "<!-- 得られるものを並べるとき用。箇条書きより強い -->",
  "<tr>",
  "  <td width=\"26\" valign=\"top\" style=\"width:26px; padding:7px 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:13px; line-height:1.9; color:{{ACCENT}};\">&#10003;</td>",
  "  <td valign=\"top\" class=\"sl-text\" style=\"padding:7px 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:15px; line-height:1.95; color:#3A3A3A;\">{{TEXT}}</td>",
  "</tr>",
  "",
  "<!-- @block statement -->",
  "<!-- 全幅。読み手の手を止めるための一行。明朝で大きく、中央に置く -->",
  "<tr>",
  "  <td class=\"sl-cream\" bgcolor=\"#FAF7F2\" style=\"background-color:#FAF7F2; margin-top:0;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      <tr><td style=\"height:1px; line-height:1px; font-size:0; background-color:#EFE7D9;\">&nbsp;</td></tr>",
  "      <tr>",
  "        <td class=\"sl-pad\" align=\"center\" style=\"padding:40px 52px 14px 52px; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:12px; line-height:1; color:#C0A16B;\">&#10022;</td>",
  "      </tr>",
  "      <tr>",
  "        <td class=\"sl-pad sl-state\" align=\"center\" style=\"padding:0 52px 42px 52px; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','MS PMincho',serif; font-size:22px; line-height:2.05; font-weight:600; letter-spacing:0.09em; color:{{ACCENT}};\">",
  "          {{TEXT}}",
  "        </td>",
  "      </tr>",
  "      <tr><td style=\"height:1px; line-height:1px; font-size:0; background-color:#EFE7D9;\">&nbsp;</td></tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block numbers -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:30px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:{{ACCENT_SOFT}}; border-radius:12px;\">",
  "      <tr>{{COLUMNS}}</tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block number-cell -->",
  "<td class=\"sl-stack\" valign=\"top\" align=\"center\" width=\"33%\" style=\"width:33%; padding:24px 10px 22px 10px;\">",
  "  <p class=\"sl-num\" style=\"margin:0 0 2px 0; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho',serif; font-size:34px; line-height:1.15; font-weight:600; letter-spacing:0.02em; color:{{ACCENT}};\">{{VALUE}}<span style=\"font-size:14px; font-weight:400; letter-spacing:0.06em;\">{{UNIT}}</span></p>",
  "  <p style=\"margin:0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:11.5px; line-height:1.75; color:#6E6558;\">{{LABEL}}</p>",
  "</td>",
  "",
  "<!-- @block voice -->",
  "<!-- 現場の声。証言は本文と質感を変えて、他人の言葉だと分かるようにする -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:30px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:#FAF7F2; border-radius:12px;\">",
  "      <tr>",
  "        <td style=\"padding:26px 26px 8px 26px;\">",
  "          <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "            <tr>",
  "              {{PHOTO}}",
  "              <td valign=\"middle\">",
  "                <p style=\"margin:0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:13px; font-weight:600; line-height:1.6; color:#3F3A32;\">{{NAME}}</p>",
  "                <p style=\"margin:0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:11px; line-height:1.7; color:#8A8072;\">{{ROLE}}</p>",
  "              </td>",
  "            </tr>",
  "          </table>",
  "        </td>",
  "      </tr>",
  "      <tr>",
  "        <td style=\"padding:0 26px 26px 26px; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho',serif; font-size:15.5px; line-height:2.1; letter-spacing:0.02em; color:#43403A;\">",
  "          <span style=\"color:#C0A16B; font-size:20px;\">&#12300;</span>{{TEXT}}<span style=\"color:#C0A16B; font-size:20px;\">&#12301;</span>",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block voice-photo -->",
  "<td width=\"60\" valign=\"middle\" style=\"width:60px; padding-right:14px;\">",
  "  <img class=\"sl-voice-img\" src=\"{{URL}}\" width=\"60\" height=\"60\" alt=\"{{NAME}}\" style=\"display:block; width:60px; height:60px; border-radius:30px; border:0;\" />",
  "</td>",
  "",
  "<!-- @block offer -->",
  "<!-- 申し込みの中身。ここだけ枠で囲って、条件が一目で読めるようにする -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:32px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border:1px solid #E7DFD2; border-radius:12px;\">",
  "      <tr><td style=\"height:4px; line-height:4px; font-size:0; background-color:#C0A16B; border-radius:12px 12px 0 0;\">&nbsp;</td></tr>",
  "      <tr>",
  "        <td style=\"padding:24px 26px 0 26px; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho',serif; font-size:17px; font-weight:600; line-height:1.7; letter-spacing:0.05em; color:{{ACCENT}};\">{{TITLE}}</td>",
  "      </tr>",
  "      <tr>",
  "        <td style=\"padding:6px 26px 26px 26px;\">{{BODY}}</td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block cta -->",
  "<!-- 全幅。行動をひとつだけ置く場所。1通に1つに絞る -->",
  "<tr>",
  "  <td bgcolor=\"{{CTA_FROM}}\" style=\"background-color:{{CTA_FROM}}; background-image:linear-gradient(135deg,{{CTA_FROM}} 0%,{{CTA_TO}} 100%);\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      <tr>",
  "        <td class=\"sl-pad\" align=\"center\" style=\"padding:40px 46px 0 46px; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho',serif; font-size:17px; line-height:1.95; letter-spacing:0.05em; color:#FFFFFF;\">",
  "          {{TEXT}}",
  "        </td>",
  "      </tr>",
  "      <tr>",
  "        <td class=\"sl-pad\" align=\"center\" style=\"padding:26px 46px 0 46px;\">",
  "          <table role=\"presentation\" class=\"sl-btn\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin:0 auto;\">",
  "            <tr>",
  "              <td align=\"center\" bgcolor=\"#C0A16B\" style=\"border-radius:6px;\">",
  "                <a href=\"{{URL}}\" target=\"_blank\" style=\"display:inline-block; padding:17px 44px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:15.5px; font-weight:600; line-height:1.3; letter-spacing:0.05em; color:#1F2A54; text-decoration:none; border-radius:6px;\">{{LABEL}}</a>",
  "              </td>",
  "            </tr>",
  "          </table>",
  "        </td>",
  "      </tr>",
  "      <tr>",
  "        <td class=\"sl-pad\" align=\"center\" style=\"padding:16px 46px 40px 46px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:11.5px; line-height:1.9; color:#D8D3E4;\">",
  "          {{SUB}}",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block button -->",
  "<tr>",
  "  <td class=\"sl-pad\" align=\"center\" style=\"padding:30px 46px 4px 46px;\">",
  "    <table role=\"presentation\" class=\"sl-btn\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin:0 auto;\">",
  "      <tr>",
  "        <td align=\"center\" bgcolor=\"{{ACCENT}}\" style=\"border-radius:6px;\">",
  "          <a href=\"{{URL}}\" target=\"_blank\" style=\"display:inline-block; padding:16px 40px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:15px; font-weight:600; line-height:1.3; letter-spacing:0.04em; color:#FFFFFF; text-decoration:none; border-radius:6px;\">{{LABEL}}</a>",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block button-outline -->",
  "<tr>",
  "  <td class=\"sl-pad\" align=\"center\" style=\"padding:14px 46px 4px 46px;\">",
  "    <table role=\"presentation\" class=\"sl-btn\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin:0 auto;\">",
  "      <tr>",
  "        <td align=\"center\" style=\"border:1px solid {{ACCENT}}; border-radius:6px;\">",
  "          <a href=\"{{URL}}\" target=\"_blank\" style=\"display:inline-block; padding:14px 34px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium',Meiryo,sans-serif; font-size:14px; font-weight:600; line-height:1.3; letter-spacing:0.04em; color:{{ACCENT}}; text-decoration:none; border-radius:6px;\">{{LABEL}}</a>",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block hero-image -->",
  "<!-- 全幅。カードの一番上に敷く写真 -->",
  "<tr>",
  "  <td style=\"font-size:0; line-height:0;\">",
  "    <img src=\"{{URL}}\" alt=\"{{ALT}}\" width=\"600\" style=\"display:block; width:100%; max-width:600px; height:auto; border:0; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:12px; line-height:1.8; color:#8A8072; text-decoration:none;\" />",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block image -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:28px 46px 0 46px;\">",
  "    <img src=\"{{URL}}\" alt=\"{{ALT}}\" width=\"508\" style=\"display:block; width:100%; max-width:508px; height:auto; border-radius:12px; border:0; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:12px; line-height:1.8; color:#8A8072; text-decoration:none;\" />",
  "    {{CAPTION}}",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block image-caption -->",
  "<p style=\"margin:9px 0 0 0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:11px; line-height:1.8; color:#8A8072;\">{{TEXT}}</p>",
  "",
  "<!-- @block note -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:24px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:{{ACCENT_SOFT}}; border-radius:10px;\">",
  "      <tr>",
  "        <td style=\"padding:20px 24px; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans','Yu Gothic Medium','Yu Gothic',Meiryo,sans-serif; font-size:14px; line-height:2.0; color:#3A3A3A;\">",
  "          {{LABEL}}{{TEXT}}",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block note-label -->",
  "<span style=\"display:block; margin-bottom:7px; font-size:10.5px; font-weight:600; letter-spacing:0.14em; color:{{ACCENT_DEEP}};\">{{TEXT}}</span>",
  "",
  "<!-- @block spec -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:22px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-top:1px solid #EDE7DD;\">",
  "      {{ROWS}}",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block spec-bare -->",
  "<!-- offer の中など、すでに枠がある場所に置くとき（左右の余白を持たない） -->",
  "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-top:1px solid #EDE7DD; margin-top:14px;\">",
  "  {{ROWS}}",
  "</table>",
  "",
  "<!-- @block spec-row -->",
  "<tr>",
  "  <td width=\"112\" valign=\"top\" class=\"sl-spec-key\" style=\"width:112px; padding:13px 10px 13px 0; border-bottom:1px solid #EDE7DD; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:12.5px; line-height:1.75; letter-spacing:0.03em; color:{{ACCENT_DEEP}}; font-weight:600;\">{{KEY}}</td>",
  "  <td valign=\"top\" style=\"padding:13px 0; border-bottom:1px solid #EDE7DD; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:14px; line-height:1.85; color:#3A3A3A;\">{{VALUE}}</td>",
  "</tr>",
  "",
  "<!-- @block divider -->",
  "<tr>",
  "  <td class=\"sl-pad\" align=\"center\" style=\"padding:36px 46px 4px 46px;\">",
  "    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin:0 auto;\">",
  "      <tr>",
  "        <td style=\"width:66px; height:1px; line-height:1px; font-size:0; background-color:#EDE7DD;\">&nbsp;</td>",
  "        <td style=\"padding:0 12px; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:12px; line-height:1; color:#C0A16B;\">&#10022;</td>",
  "        <td style=\"width:66px; height:1px; line-height:1px; font-size:0; background-color:#EDE7DD;\">&nbsp;</td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block quote -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:26px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      <tr>",
  "        <td style=\"padding:4px 0 4px 22px; border-left:3px solid #E6D3A8; font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho',serif; font-size:15.5px; line-height:2.05; letter-spacing:0.02em; color:#544F46;\">",
  "          {{TEXT}}{{CITE}}",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block quote-cite -->",
  "<span style=\"display:block; margin-top:9px; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:11.5px; letter-spacing:0.03em; color:#8A8072;\">&#8212;&nbsp;{{TEXT}}</span>",
  "",
  "<!-- @block cards -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:26px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "      <tr>{{COLUMNS}}</tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block card-column -->",
  "<td class=\"sl-stack\" width=\"50%\" valign=\"top\" style=\"width:50%; padding:0 5px;\">",
  "  <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:#FAF7F2; border-radius:10px;\">",
  "    <tr><td style=\"height:3px; line-height:3px; font-size:0; background-color:{{ACCENT}}; border-radius:10px 10px 0 0;\">&nbsp;</td></tr>",
  "    <tr>",
  "      <td style=\"padding:18px 20px 20px 20px;\">",
  "        <p style=\"margin:0 0 7px 0; font-family:'Hiragino Mincho ProN','Yu Mincho',serif; font-size:15.5px; font-weight:600; line-height:1.6; letter-spacing:0.04em; color:{{ACCENT}};\">{{TITLE}}</p>",
  "        <p style=\"margin:0; font-family:'Hiragino Kaku Gothic ProN',Meiryo,sans-serif; font-size:13px; line-height:1.9; color:#5C564D;\">{{TEXT}}</p>",
  "      </td>",
  "    </tr>",
  "  </table>",
  "</td>",
  "",
  "<!-- @block ps -->",
  "<!-- 追伸。本文を飛ばした人が最後に読む場所なので、要点をもう一度置く -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:34px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:#FCFAF6; border-radius:10px;\">",
  "      <tr>",
  "        <td width=\"4\" style=\"width:4px; background-color:#C0A16B; border-radius:10px 0 0 10px; font-size:0; line-height:0;\">&nbsp;</td>",
  "        <td style=\"padding:20px 24px;\">",
  "          <p style=\"margin:0 0 6px 0; font-family:'Hiragino Mincho ProN','Yu Mincho',serif; font-size:13px; font-weight:600; letter-spacing:0.14em; color:#9A7F4E;\">追伸</p>",
  "          <p style=\"margin:0; font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:14px; line-height:2.0; color:#43403A;\">{{TEXT}}</p>",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block signature -->",
  "<tr>",
  "  <td class=\"sl-pad\" style=\"padding:36px 46px 0 46px;\">",
  "    <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-top:1px solid #EDE7DD;\">",
  "      <tr>",
  "        <td style=\"padding:22px 0 0 0;\">",
  "          <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">",
  "            <tr>",
  "              {{PHOTO}}",
  "              <td valign=\"top\" style=\"font-family:'Hiragino Kaku Gothic ProN','Hiragino Sans',Meiryo,sans-serif; font-size:13px; line-height:2.0; color:#5C564D;\">",
  "                {{TEXT}}",
  "              </td>",
  "            </tr>",
  "          </table>",
  "        </td>",
  "      </tr>",
  "    </table>",
  "  </td>",
  "</tr>",
  "",
  "<!-- @block signature-photo -->",
  "<td width=\"70\" valign=\"top\" style=\"width:70px; padding-right:16px;\">",
  "  <img src=\"{{URL}}\" width=\"56\" height=\"56\" alt=\"\" style=\"display:block; width:56px; height:56px; border-radius:28px; border:0;\" />",
  "</td>",
  "",
  "<!-- @block spacer -->",
  "<tr><td style=\"height:{{SIZE}}px; line-height:{{SIZE}}px; font-size:0;\">&nbsp;</td></tr>",
  ""
].join('\n');

/** 配色テーマ（themes.json） */
const TEMPLATE_THEMES = {
  "daily": {
    "label": "日刊（読み物）",
    "eyebrow": "日刊　現場から",
    "accent": "#41564C",
    "accentDeep": "#5C7C6F",
    "accentSoft": "#EDF2F0",
    "ctaFrom": "#41564C",
    "ctaTo": "#5C7C6F",
    "base": "daily",
    "note": "平日毎日の読み物。売らない・教えない・オチをつけない。1本600〜900字。CTAは置かない（売り込みは月1の営業レターに任せる）。"
  },
  "b2b": {
    "label": "事業所向け ご案内レター",
    "eyebrow": "STELLIZE ─ 就労支援の現場へ",
    "accent": "#1F2A54",
    "accentDeep": "#2E3A66",
    "accentSoft": "#EEF0F7",
    "ctaFrom": "#1F2A54",
    "ctaTo": "#2E3A66",
    "note": "就労支援事業所へのご案内。ネイビー×ゴールドで信頼を先に立てる。用件を先に、CTAは1つに絞る。",
    "base": "default"
  },
  "newsletter": {
    "label": "メルマガ（定期便）",
    "eyebrow": "STELLIZE NEWSLETTER",
    "accent": "#5A4C7D",
    "accentDeep": "#6F5F96",
    "accentSoft": "#F3F0F8",
    "ctaFrom": "#6F5F96",
    "ctaTo": "#8E7DB2",
    "note": "定期的に送る号。読み物として長くなってよい。ラベンダーを主役に。",
    "base": "default"
  },
  "partner": {
    "label": "パートナー・社内向け レポート",
    "eyebrow": "PARTNER REPORT",
    "accent": "#41564C",
    "accentDeep": "#5C7C6F",
    "accentSoft": "#EDF2F0",
    "ctaFrom": "#41564C",
    "ctaTo": "#5C7C6F",
    "note": "提携先・関係者への定期報告。数字と事実を淡々と並べる。",
    "base": "default"
  },
  "announce": {
    "label": "お知らせ・募集（単発）",
    "eyebrow": "ANNOUNCEMENT",
    "accent": "#9A4D66",
    "accentDeep": "#B85F7C",
    "accentSoft": "#FBEFF3",
    "ctaFrom": "#B85F7C",
    "ctaTo": "#D0879E",
    "note": "新サービス・イベント告知など、単発で目を引かせたいとき。",
    "base": "default"
  }
};
